# Generated by Django 4.0.6 on 2022-08-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_delete_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
